"""empty message

Revision ID: 014aefdeed72
Revises: 7ac6f90378bf
Create Date: 2020-08-28 10:14:50.570209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014aefdeed72'
down_revision = '7ac6f90378bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=140), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=120), nullable=True))

    op.drop_table('attachment')
    # ### end Alembic commands ###
