"""empty message

Revision ID: 1b5c0ce7a795
Revises: 58df75045a37
Create Date: 2020-08-07 20:36:13.297302

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1b5c0ce7a795'
down_revision = '58df75045a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
