"""empty message

Revision ID: 353cac3c2f3d
Revises: 0791c6e43308
Create Date: 2020-08-06 15:55:05.288446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353cac3c2f3d'
down_revision = '0791c6e43308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
