"""empty message

Revision ID: 451191a8ba6c
Revises: cfa50a3624b9
Create Date: 2020-08-07 21:36:05.015850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451191a8ba6c'
down_revision = 'cfa50a3624b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
