"""empty message

Revision ID: 89dd450d71b7
Revises: 
Create Date: 2020-07-21 15:32:26.902608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dd450d71b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority', sa.String(length=30), nullable=True))
    op.add_column('tickets', sa.Column('status', sa.String(length=30), nullable=False))
    op.drop_column('tickets', 'answer_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('answer_text', sa.TEXT(), nullable=True))
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
