"""empty message

Revision ID: c5a92d5ac086
Revises: 2759e6709178
Create Date: 2020-08-18 08:17:40.640051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a92d5ac086'
down_revision = '2759e6709178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
