"""empty message

Revision ID: ded54e0e55a8
Revises: e062b53cf058
Create Date: 2020-08-17 23:30:10.301893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded54e0e55a8'
down_revision = 'e062b53cf058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('comment', 'parent_id')
    op.drop_column('comment', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('path', sa.TEXT(), nullable=True))
    op.add_column('comment', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('files')
    # ### end Alembic commands ###
