"""empty message

Revision ID: e062b53cf058
Revises: 6796a7938ff4
Create Date: 2020-08-14 19:00:45.439939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e062b53cf058'
down_revision = '6796a7938ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.alter_column('comment', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
