"""empty message

Revision ID: f05a0bb3eaef
Revises: 3ef75cc854dc
Create Date: 2020-08-07 20:50:24.750690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05a0bb3eaef'
down_revision = '3ef75cc854dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('path', sa.Text(), nullable=True))
    op.alter_column('comment', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.alter_column('comment', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comment', 'path')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###
