"""empty message

Revision ID: fc4f09d216a0
Revises: 3280dd894da0
Create Date: 2020-08-17 23:33:26.527395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4f09d216a0'
down_revision = '3280dd894da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'parent_id')
    op.drop_column('comment', 'path')
    op.alter_column('files', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('files', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('comment', sa.Column('path', sa.TEXT(), nullable=True))
    op.add_column('comment', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
